# Generated by Django 2.2.4 on 2019-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cardrule', models.CharField(max_length=32)),
                ('cardnum', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('loandate', models.CharField(max_length=32)),
                ('active', models.CharField(max_length=32)),
                ('emailuser', models.CharField(max_length=100)),
                ('emailpwd', models.CharField(max_length=100)),
                ('wecatpwd', models.CharField(max_length=100)),
                ('wecatpay', models.CharField(max_length=100)),
                ('qquser', models.CharField(max_length=100)),
                ('qqpwd', models.CharField(max_length=100)),
                ('dec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phonename', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('loandate', models.CharField(max_length=32)),
                ('dec', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
