# Generated by Django 2.0.5 on 2018-05-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonename', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('loandate', models.CharField(max_length=32)),
            ],
        ),
    ]
