# Generated by Django 2.0.5 on 2018-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_phoneinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinfo',
            name='dec',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
