# Generated by Django 2.0.5 on 2018-05-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_phoneinfo_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneinfo',
            name='os',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
